# Generated by Django 3.0.5 on 2020-04-08 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_text', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date planned')),
            ],
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=66)),
                ('student_names', models.CharField(max_length=300)),
                ('demoday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demodays.DemoDay')),
            ],
        ),
    ]
