# Generated by Django 3.0.5 on 2020-04-19 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('linkedin', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_in_school', models.CharField(choices=[('PRB', 'ProgBasics'), ('SEC', 'Second Module'), ('TRD', 'Third Module'), ('ADV', 'Advance Module'), ('JBH', 'Job Hunt'), ('ALU', 'Alumni')], default='TRD', max_length=3)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('nick', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('students', models.ManyToManyField(blank=True, to='demodays.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Demoday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='demodays.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('presentation', models.FileField(blank=True, upload_to='demodays/presentation_files')),
                ('demoday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demodays.Demoday')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demodays.ProjectTeam')),
                ('used_tech', models.ManyToManyField(blank=True, to='demodays.Tech')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='representatives',
            field=models.ManyToManyField(blank=True, to='demodays.Representative'),
        ),
        migrations.AddField(
            model_name='company',
            name='sought_techs',
            field=models.ManyToManyField(blank=True, to='demodays.Tech'),
        ),
    ]
