# Generated by Django 3.0.5 on 2020-04-19 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demodays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoday',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='demodays.Company'),
        ),
    ]
