# Generated by Django 3.0.5 on 2020-04-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demodays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demoday',
            name='is_upcoming',
        ),
    ]
